CC = gcc
CFLAGS = -Wall -g -I./include -I./hal/inc
LDFLAGS = -lm

# 簡單目標
simple: simple_test

simple_test: simple_test.c
	$(CC) $(CFLAGS) -o $@ $< $(LDFLAGS)

clean:
	rm -f simple_test *.o

test: simple_test
	./simple_test

.PHONY: clean test simple
